# Example: Multi-Architecture Build with Attestation
#
# This workflow builds for multiple architectures and attests each binary.

name: Multi-Arch Build and Attest

on:
  push:
    tags: ["v*"]

jobs:
  build-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
        exclude:
          - os: ubuntu-latest
            arch: arm64 # Cross-compile instead
        include:
          - os: ubuntu-latest
            arch: arm64
            cross: true

    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build binary
        run: |
          GOOS=${{ matrix.os == 'macos-latest' && 'darwin' || 'linux' }} \
          GOARCH=${{ matrix.arch }} \
          go build -trimpath -buildvcs \
            -ldflags="-s -w -X main.version=${{ github.ref_name }}" \
            -o myapp-${{ matrix.os }}-${{ matrix.arch }} \
            ./cmd/myapp

      - name: Install Provenix
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            curl -sSL https://github.com/open-verix/provenix/releases/download/v0.1.0/provenix-linux-amd64 -o provenix
          else
            curl -sSL https://github.com/open-verix/provenix/releases/download/v0.1.0/provenix-darwin-arm64 -o provenix
          fi
          chmod +x provenix

      - name: Initialize Provenix
        run: ./provenix init

      - name: Attest binary
        run: |
          ./provenix attest myapp-${{ matrix.os }}-${{ matrix.arch }} \
            --format cyclonedx-json \
            --output attestation-${{ matrix.os }}-${{ matrix.arch }}.json

      - name: Verify attestation
        run: ./provenix verify attestation-${{ matrix.os }}-${{ matrix.arch }}.json

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            myapp-${{ matrix.os }}-${{ matrix.arch }}
            attestation-${{ matrix.os }}-${{ matrix.arch }}.json
