# Example: Policy-Driven Build Gate
#
# This workflow fails the build if security policy violations are detected.

name: Security Policy Gate

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  security-check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write # Comment on PRs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build application
        run: go build -o myapp ./cmd/myapp

      - name: Install Provenix
        run: |
          curl -sSL https://github.com/open-verix/provenix/releases/download/v0.1.0/provenix-linux-amd64 -o provenix
          chmod +x provenix

      - name: Initialize Provenix
        run: ./provenix init

      - name: Generate attestation
        run: |
          ./provenix attest myapp \
            --format cyclonedx-json \
            --output attestation.json \
            --skip-transparency  # Don't publish to Rekor for PR builds

      - name: Check security policy
        id: policy-check
        run: |
          # This will exit 1 if policy violations are found
          ./provenix policy check --attestation attestation.json --config provenix.yaml || echo "POLICY_FAILED=true" >> $GITHUB_OUTPUT

      - name: Generate VEX document for triaged issues
        if: steps.policy-check.outputs.POLICY_FAILED == 'true'
        run: |
          ./provenix vex create attestation.json \
            --output vex.json

      - name: Generate security report
        run: |
          ./provenix report attestation.json \
            --format markdown \
            --output SECURITY-REPORT.md

      - name: Comment on PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('SECURITY-REPORT.md', 'utf8');
            const policyFailed = '${{ steps.policy-check.outputs.POLICY_FAILED }}' === 'true';

            const header = policyFailed 
              ? '## ⚠️ Security Policy Violations Detected' 
              : '## ✅ Security Policy Check Passed';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${header}\n\n${report}`
            });

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-artifacts
          path: |
            attestation.json
            SECURITY-REPORT.md
            vex.json

      - name: Fail build if policy violations found
        if: steps.policy-check.outputs.POLICY_FAILED == 'true'
        run: |
          echo "::error::Security policy violations detected. Review SECURITY-REPORT.md for details."
          exit 1
